### ISSUE TITLE
drop points not updateable after some time of inactivity

### ISSUE THREAD

**Issue by karolherbst** [c3bottles/c3bottles#130]
the status of drop points can't be changed after a while. That usually happens for coordinators who keep the website open for a longer time. Reloading the page helps.

**Comment by MichiK** [comment]
That is most probably due to the CSRF protection. I have code for that in another (private) project that polls the API at an interval, receives a fresh CSRF token and updates all forms so that the website can stay open indefinitely (as long as the server isn't unreachable for too long so that it can't get a fresh token in time).

However, I first have to understand all that fancy JS stuff...
